# Generated by Django 6.0.2 on 2026-03-05 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GPU",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model", models.CharField(max_length=100)),
                ("name", models.IntegerField()),
                ("VRAM", models.ImageField(upload_to="")),
            ],
        ),
        migrations.DeleteModel(
            name="Product",
        ),
    ]
