# Generated by Django 6.0.2 on 2026-03-05 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_gpu_delete_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gpu",
            name="VRAM",
            field=models.IntegerField(),
        ),
    ]
