# Generated by Django 6.0.2 on 2026-03-04 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("address", models.TextField()),
                ("email", models.EmailField(max_length=254)),
                ("website", models.URLField()),
                ("age", models.IntegerField()),
                ("phoneNumber", models.BigIntegerField()),
                ("price", models.PositiveIntegerField()),
                ("tax", models.DecimalField(decimal_places=5, max_digits=10)),
                ("temperature", models.FloatField()),
                ("DOB", models.DateField()),
                ("created_date", models.DateField(auto_now_add=True)),
                ("updated_date", models.DateField(auto_now=True)),
                ("interview_time", models.TimeField()),
                ("DOB_and_time", models.DateTimeField()),
                ("duration", models.DurationField()),
                ("image", models.ImageField(upload_to="")),
                ("file", models.FileField(upload_to="")),
                ("is_active", models.BooleanField(default=True)),
                ("email_verified", models.BooleanField(blank=True, null=True)),
                ("skills", models.JSONField(default=dict)),
                (
                    "degree",
                    models.CharField(
                        choices=[
                            ("highschool", "High School"),
                            ("bachelor", "Bachelor's"),
                            ("master", "Master's"),
                            ("phd", "PhD"),
                            ("diploma", "Diploma"),
                        ]
                    ),
                ),
            ],
        ),
    ]
