# Generated by Django 6.0.2 on 2026-03-04 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="slug",
            field=models.SlugField(default="default-slug", unique=True),
        ),
    ]
